export const ActionTypes = {
    GET_INITIATE_LOGIN: 'GET_INITIATE_LOGIN',
    SET_INITIATE_LOGIN: 'SET_INITIATE_LOGIN',
    SET_LOCKED_ACCOUNT: 'SET_LOCKED_ACCOUNT',
  
    GET_INITIATE_LOGOUT: 'GET_INITIATE_LOGOUT',
    ERROR_INITIATE_LOGOUT: 'ERROR_INITIATE_LOGOUT',
  
    SET_USER_DATA: 'SET_USER_DATA',
  
    SET_USER_LOGGER_DATA: 'SET_USER_LOGGER_DATA',
    SEND_SERVICE_LOGGER: 'SEND_SERVICE_LOGGER',
  
    GET_LOGIN_STATUS: 'GET_LOGIN_STATUS',
    SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
  
    SET_AUTH_TYPE: 'SET_AUTH_TYPE',
  
    GET_USER_DATA: 'GET_USER_DATA',
    LOGOUT_USER_DATA: 'LOGOUT_USER_DATA',
  
    GET_APP_DATA: 'GET_APP_DATA',
  
    START_INITIATE_LOGIN: 'START_INITIATE_LOGIN',
    LOGOUT_USER_LOGIN: 'LOGOUT_USER_LOGIN',
  
    GET_BIO_STATUS: 'GET_BIO_STATUS',
    SET_BIO_STATUS: 'SET_BIO_STATUS',
  
    SAVE_LOGIN_STATUS: 'SAVE_LOGIN_STATUS',
  
    SAVE_BIO_STATUS: 'SAVE_BIO_STATUS',
  
    SAVE_AUTH_TYPE: 'SAVE_AUTH_TYPE',
  
    SAVE_USER_DATA: 'SAVE_USER_DATA',
    SAVE_USERPROFILE_DATA: 'SAVE_USERPROFILE_DATA',
    SET_KEYBOARD_HEIGHT: 'SET_KEYBOARD_HEIGHT',
  
    SET_LAST_SCREEN: 'SET_LAST_SCREEN',
  
    SET_SAFEAREA_INSETS: 'SET_SAFEAREA_INSETS',
  
    START_FORGOT_PASSWORD: 'START_FORGOT_PASSWORD',
    GET_FORGOT_PASSWORD: 'GET_FORGOT_PASSWORD',
    SET_FORGOT_PASSWORD: 'SET_FORGOT_PASSWORD',
    RESET_FORGOT_PASSWORD_LOADING: 'RESET_FORGOT_PASSWORD_LOADING',
  
    START_OTP_VERIFICATION: 'START_OTP_VERIFICATION',
    GET_OTP_VERIFICATION: 'GET_OTP_VERIFICATION',
    SET_OTP_VERIFICATION: 'SET_OTP_VERIFICATION',
  
    ERROR_INITIATE_LOGIN: 'ERROR_INITIATE_LOGIN',
  
    ERROR_FORGOT_PASSWORD: 'ERROR_FORGOT_PASSWORD',
  
    ERROR_OTP_VERIFICATION: 'ERROR_OTP_VERIFICATION',
    GET_FETCH_CONFIGURATION:'GET_FETCH_CONFIGURATION',
    ERROR_FETCH_CONFIGURATION:'ERROR_FETCH_CONFIGURATION',
    SET_FETCH_CONFIGURATION:'SET_FETCH_CONFIGURATION',
    START_FETCH_CONFIGURATION:'START_FETCH_CONFIGURATION'
}